### ISSUE TITLE
Feature: Windows Menubar

### ISSUE THREAD

**Issue by ch1n3du** [atomCAD/atomCAD#21]
I'm currently working on a small prototype to learn how to add a menubar to a Windows `winit` app, once I can get it to match the functionality of the MacOS menubar, I'll fork the repo and add my code.

**Comment by ch1n3du** [comment]
I've encountered some issues and will make a fork to make sharing them easier.

**Comment by ch1n3du** [comment]
My main issue is that Menubars in Windows have to be declared when creating the window and I've not found a workaround so far that fits with the current workflow of creating a window and then calling `setup_menu_bar` on it.

**Comment by ch1n3du** [comment]
I just found out there's a fork of `winit` called Tao that allows a lot more access to the Windows API and changed default support on Linux to GTK, it looks pretty much like a drop-in replacement and can make option 2 feasible.

**Comment by maaku** [comment]
Tau isn't really a replacement for `winit`. It's more a framework for writing standalone browser-based apps, like Electron but with Rust instead of Javascript. I investigated using Tau/tauri, but upstream winit is better maintained and better integrated into the Rust native library ecosystem, like `wgpu`.

AFAIK what you want to do is natively supported by `winit`. There is a Windows extension interface that adds a `get_hwnd()` method to the window object, which you use to retrieve the window handle. You should then be able to use one of the various Rust crates for interfacing with the win32 api to create a menubar and attach it to that window.

See:

https://docs.rs/winit/0.19.5/i686-pc-windows-msvc/winit/os/windows/trait.WindowExt.html

**Comment by ch1n3du** [comment]
Thanks, the `get_hwnd()` solves my issue, this is my first time using both  `winit` and `win32` so I wasn't aware they supported that.

**Comment by maaku** [comment]
Yeah it's not obvious. I wouldn't have known except that the situation was the same on macOS--there's an Apple-specific trait you have to include over there to get a Cocoa handle for the window.

Same thing on X11 too, although it turns out there are some complications there which might be show stopping. See #20

**Comment by ch1n3du** [comment]
![image](https://github.com/atomCAD/atomCAD/assets/38131869/e39caf65-6b10-4843-871c-62a8e854049c)
I want to confirm if this is the desired look for menubar I've not been able to see the MacOS version for comparison, everything is in a popup submenu because of the initial nested submenu [here](https://github.com/atomCAD/atomCAD/blob/1c220000afe30a7e90bd81af5aa20a5fe179e7f9/src/menubar.rs#L115)

**Comment by ch1n3du** [comment]
I've been able to make a lot of progress [here](https://github.com/ch1n3du/atomCAD/blob/main/src/platform_impl/windows/menubar.rs) and I currently only have two major blockers:

## 1. The AtomCAD window crashes whenever it is minimized.

I noticed this when implementing the `SystemAction::HideApp` functionality. It crashes with the following error message:

```sh
   Compiling atomcad v0.1.0 (C:\Users\USER\Code\trying_stuff\atomCAD)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 00s
     Running `target\debug\atomcad.exe`
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.
', C:\Users\USER\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.17.0\src\backend\direct.rs:771:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\atomcad.exe` (exit code: 101)
```
I haven't found a solution yet but I think these GH issues might be helpful:

- https://github.com/rust-windowing/winit/issues/2308
- https://github.com/bevyengine/bevy/issues/1457

### Steps to recreate (on Windows)

1. Make sure to install the [build dependencies for windows](https://github.com/atomCAD/atomCAD#to-run)

2. Clone the repo

   ```sh
   $ git clone https://github.com/atomCAD/atomCAD
   ```

2. Run the app

   ```sh
   $ cd atomCAD
   $ cargo run
   ```
3. Minimize the window.

## 2. Adding shortcuts needs access to the `EventLoopBuilder`

To the shortcuts to the menu, I have to use the `TranslateAcceleratorW` ([MSDocs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-translateacceleratorw#parameters), [Rust bindings docs](https://docs.rs/windows-sys/0.48.0/windows_sys/Win32/UI/WindowsAndMessaging/fn.TranslateAcceleratorW.html)) function,
it's second argument is a pointer to  pointer an [MSG](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-msg) structure that contains message information retrieved from the calling thread's message queue. 

The only way to access this msg pointer is through the [`winit::EventLoopBuilderExtWindows::with_msg_hook` method](https://github.com/rust-windowing/winit/blob/d68d9eab38b98b4e55a604a1d919adc2ea0929e5/src/platform/windows.rs#L84). An example of how this might looks is [this line](https://github.com/tauri-apps/muda/blob/4a41e5231ed6150c07945a29c9af566f7f8ca03c/examples/winit.rs#L29) in muda's winit example. I haven't been able to find a workaround for accessing it and from going through winit's source code it doesn't seem to be exposed anywhere else.

**Comment by maaku** [comment]
1. I think I know what is going on here. Basically you need to shut down the rendering loop while the window is suspended / doesn't exist. However you probably just shouldn't be implementing the "Hide atomCAD", "Hide Others" and "Show All" menu items, as that's macOS-specific. Either we should filter those on the front-end so they are not passed to your code, or your code should ignore (and not generate) those menus.

2. Ok so we need to pass the `EventLoopBuilder` to the platform code, just like we pass the `Window`. I'll make this change.

**Comment by ch1n3du** [comment]
I'm currently ignoring the unsupported menu items but they look weird with the dangling `MenuItem::Separator`s.

**Comment by maaku** [comment]
Oh wait the event loop builder has to be created before the event loop, and the event loop builder is needed to create the window. So we can't pass the event loop builder *and* the window to the platform code. We need a new API, or rearchitect things somehow.

The event loop is created in `main.rs`. Can we do the `with_msg_hook` thing there? (By creating a new `main()` for windows targets.) But that would require having access to the accelerators to pass to `TranslateAcceleratorW`. Maybe those can be accessed from behind a `Rc` or `Arc`? I'll push this back to you since you know more about how Windows message loops do than I, as I haven't done win32 coding in 25 years.

**Comment by maaku** [comment]
Either we should add a `prepare_event_loop` function to `src/menubar.rs` which takes an `EventLoopBuilder`, or we should put that logic in `src/main.rs` and just have some way of fetching the accelerators within the event loop hook that you add. I'll leave the choice up to you.

**Comment by ch1n3du** [comment]
This is actually my first time using the Win32 API but I think having the `prepare_event_loop` function would be better in the long-term as even the MacOS `EventLoop` has special configurations.

**Comment by maaku** [comment]
This is turning out to be vastly more complicated than I had assumed. The Gtk implementation of menubar support in #20 is stalled for other, unrelated but challenging reasons as well. With that in mind I think maybe it does make sense to add a dependency for menubar management, and [muda](https://crates.io/crates/muda) does look like a well-maintained crate for that purpose with minimal dependencies. Thanks for finding that as an option, and sorry for taking a while to come to that view.

I suggest that this issue be used to track implementing menubar support on Windows using muda, and then once that is working we can think about extending support to macOS and Linux/Gtk.

**Comment by ch1n3du** [comment]
# Challenges with integrating Muda

I'm writing this because after inspecting the example I've seen that integrating the `muda` library would need a non-trivial change in how the menubar works I want to document them to avoid making the wrong choice. the biggest change would be that the `muda::Menu` value has to remain to scope as it holds data necessary for the menu to work and would deallocate them when dropped so it would have to be returned from whatever function builds the menu.

## Current Approach

1. AtomCAD's `main` function:
	- Builds an `EventLoop` 
	- Calls  the  `atomCAD::start(EventLoop)` function.
```mermaid
stateDiagram-v2
      [*] --> main()
      main() --> start(EventLoop) : (EventLoop) 
	  start(EventLoop) --> [*]
```
2. The `atomCAD::start(EventLoop)` then:
	- Creates a `Window`.
	- Calls `atomCAD::menubar::setup_menu_bar(&Window)`  which:
		- Creates an `atomCAD::Menu`
		- Calls `atomCAD::platform::attach_menu_bar(&Window, atomCAD::Menu)`
	- Calls `atomCAD::run(EventLoop, Option<Window>)`

```mermaid
stateDiagram-v2
      [*] --> start(EventLoop)
	  
      start(EventLoop) --> setup_menu_bar(&Window) : (&Window) 
	  setup_menu_bar(&Window) --> attach_menu_bar(&Window,Menu) : (&Window,Menu) 
   
      attach_menu_bar(&Window,Menu) --> setup_menu_bar(&Window)
	  setup_menu_bar(&Window) --> start(EventLoop)
   
	  start(EventLoop) --> run(EventLoop,Window)
      run(EventLoop,Window) --> [*]
```
### Full Diagram of the Current Approach
```mermaid
stateDiagram-v2
      [*] --> main()
      main() --> start(EventLoop) : (EventLoop) 
	  
      start(EventLoop) --> setup_menu_bar(&Window) : (&Window) 
	  setup_menu_bar(&Window) --> attach_menu_bar(&Window,Menu) : (&Window,Menu) 
   
      attach_menu_bar(&Window,Menu) --> setup_menu_bar(&Window)
	  setup_menu_bar(&Window) --> start(EventLoop)
   
	  start(EventLoop) --> run(EventLoop,Window)
      run(EventLoop,Window) --> [*]
	  
```

### Relevant Functions/Types
- `muda::Menu`: Platform-independent menu type defined in [`src/menubar.rs`](https://github.com/atomCAD/atomCAD/blob/2e4976354d9fc6bda6b59483d6684ecd8adcd4e9/src/menubar.rs#L15)
- `atomCAD::start(EventLoop<()>)`: Accepts an `EventLoop`, creates the application window, calls `setup_menu_bar(&Window)` passing it a reference to application window, finally it calls `run(EventLoop, Option<Window>)`.
   - `atomCAD::menubar::setup_menu_bar(&Window)`: Creates an `atomCAD::menubar::Menu` and then calls `attach_menu(&Window, Menu)` with the application window and the created menu.
	  - `atomCAD::menubar::attach_menu(&Window, Menu)`: Implements platform dependent logic to add an `atomCAD::menubar::Menu` to the `Window`.
- `atomCAD::run(EventLoop, Option<Window>)`: Handles the application loop.

### Issues with the current approach
1. Platforms need the `EventLoopBuilder` for certaing functionality 


## Proposed Muda integration approach

### Diagram
1. AtomCAD's `main` function:
	- Builds an `EventLoop` 
	- Calls  the  `atomCAD::start()` function.
 ```mermaid
stateDiagram-v2
      main() --> start()
	  start() --> [*]
```

- `atomCAD::start()`: Creates an `EventLoopBuilder`,  it calls `atomCAD::menubar::create_menu(&mut EventLoop) -> madu::Menu` which creates a `madu::Menu`, it then creates a `Window` and calls `atomCAD::menubar::attach_menu(&Window, &Menu)`, finally it calls `run(EventLoop, Option<Window>)`.
```mermaid
stateDiagram-v2
    [*] --> start()
	start() --> create_menu(&mut_EventLoop) : (&mut_EventLoop)
    create_menu(&mut_EventLoop) --> start() : Menu

    start() --> attach_menu(&Window,&Menu)
	attach_menu(&Window,&Menu) --> start()
 
    start() --> run(EventLoop,Window) : (EventLoop,Window)
	run(EventLoop,Window) --> [*]
```

- `atomCAD::run(EventLoop, Option<Window>)`: Handles the application loop.

### Relevant Function/Types
- `muda::Menu`: Platform-independent menu type defined in  Muda.

### Benefits of Muda
- The Muda library is platform independent enough that all the code for MacOS and Windows specific code could be neatly fit into a module the size of `src/menubar.rs` the only platform specific code needed would be a function to handle the platform-dependent `EventLoopBuilder` logic.

### Disadvantages of Muda

- It doesn't support Android, iOS and Web, I personally don't think this is an issue as those platforms probably wouldn't need a menubar but it's important to note.

- It only supports GTK for Linux and @tidux mentioned a lot of potential issues with that in #20, I attempted building the `muda` on my Ubuntu WSL and it crashed because of missing dependencies, the error message was:

```sh
The following warnings were emitted during compilation:

warning: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "libsoup-3.0" "libsoup-3.0 >= 3.0"` did not exit successfully: exit status: 1

error: failed to run custom build command for `soup3-sys v0.3.1`

Caused by:
  process didn't exit successfully: `/home/ch1n3du/Code/muda/target/debug/build/soup3-sys-bc10f1a4a4e9bc12/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBSOUP_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "libsoup-3.0" "libsoup-3.0 >= 3.0"` did not exit successfully: exit status: 1
  error: could not find system library 'libsoup-3.0' required by the 'soup3-sys' crate

  --- stderr
  Package libsoup-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libsoup-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libsoup-3.0' found
  Package libsoup-3.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libsoup-3.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libsoup-3.0' found

warning: build failed, waiting for other jobs to finish...
```

**Comment by poopsicles** [comment]
@ch1n3du maybe you need to `apt install libsoup-3.0-dev`? that might provide `libsoup-3.0.so` or something
